version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: maestro-demo-dev:latest
    container_name: maestro-demo-dev
    # Security constraints
    user: nobody
    read_only: true
    network_mode: none
    # Mount /tmp as writable volume
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    volumes:
      - .:/workspace:ro
      # Allow writing to workspace for Go builds (override read-only)
      - .:/workspace
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
      - GOPATH=/go
    stdin_open: true
    tty: true
    working_dir: /workspace
    # No port mappings - networking disabled
    command: tail -f /dev/null
